package com.tinyurl.orchestration.model;

public enum PolicyAction {
    INSPECT_REPOSITORY,
    ANALYZE_REQUIREMENT,
    CREATE_PLAN,
    EDIT_FEATURE_CODE,
    GENERATE_TESTS,
    RUN_LOCAL_TESTS,
    CHANGE_PUBLIC_API,
    MODIFY_DATABASE_SCHEMA,
    ADD_RUNTIME_DEPENDENCY,
    COMMIT_CHANGES,
    PUSH_BRANCH,
    DEPLOY,
    FORCE_PUSH,
    MODIFY_PRODUCTION_DATA
}
