package com.tinyurl.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

import java.sql.DriverManager;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayDataPreservationIntegrationTest {

    @Test
    void baselinesExistingSchemaWithoutLosingRows() throws Exception {
        String url = databaseUrl("legacy");
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE url_mapping (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      short_code VARCHAR(12) NOT NULL,
                      original_url VARCHAR(2048) NOT NULL,
                      created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                      redirect_count BIGINT NOT NULL DEFAULT 0,
                      last_accessed_at TIMESTAMP WITH TIME ZONE,
                      expires_at TIMESTAMP WITH TIME ZONE,
                      CONSTRAINT uk_url_mapping_short_code UNIQUE (short_code)
                    )
                    """);
            statement.executeUpdate("""
                    INSERT INTO url_mapping
                      (short_code, original_url, created_at, redirect_count)
                    VALUES ('legacy01', 'https://example.com/legacy',
                            TIMESTAMP WITH TIME ZONE '2026-01-01 00:00:00+00', 7)
                    """);
        }

        migrate(url);

        try (var connection = DriverManager.getConnection(url, "sa", "");
             var rows = connection.createStatement().executeQuery(
                     "SELECT original_url, redirect_count FROM url_mapping WHERE short_code='legacy01'")) {
            assertThat(rows.next()).isTrue();
            assertThat(rows.getString("original_url")).isEqualTo("https://example.com/legacy");
            assertThat(rows.getLong("redirect_count")).isEqualTo(7);
        }
    }

    @Test
    void createsCurrentSchemaForCleanDatabase() throws Exception {
        String url = databaseUrl("clean");

        var result = migrate(url);

        assertThat(result.migrationsExecuted).isEqualTo(1);
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var columns = connection.getMetaData().getColumns(null, null, "URL_MAPPING", "EXPIRES_AT")) {
            assertThat(columns.next()).isTrue();
        }
    }

    private org.flywaydb.core.api.output.MigrateResult migrate(String url) {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("1")
                .validateOnMigrate(true)
                .load()
                .migrate();
    }

    private String databaseUrl(String prefix) {
        return "jdbc:h2:mem:" + prefix + "-" + UUID.randomUUID() +
                ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE";
    }
}
