ALTER TABLE url_mapping ADD COLUMN expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE url_mapping ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE url_mapping ADD COLUMN deactivated_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE redirect_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(12) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer_host VARCHAR(255),
    client_category VARCHAR(32) NOT NULL
);

CREATE INDEX idx_redirect_event_code_time
    ON redirect_event (short_code, occurred_at);
